---
# tasks file for teamviewer
# https://community.teamviewer.com/t5/Knowledge-Base-EN/How-to-update-TeamViewer-on-Linux-via-repository/ta-p/30666
- name: Include variables based on the operating system 
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: True 
  block:
  - include_tasks: "install-{{ ansible_os_family }}.yml"